#include<iostream.h>
#include "3lab.h"

void main(void){
		 clrscr();
		 long V,S,H;Time t1,t2,t3;
		 cout<<"Домашнее задание:";
		 cout<<"\nПроверка реализации перегрзуки <</>> для моего класса Time:";
		 cout<<"\nПодсказка время вводить через двухиточие (:)!!!";
		 cout<<"\nВведите время t1 =>";
		 cin>>t1;
		 cout<<"Введите время t2 =>";
		 cin>>t2;
		 clrscr();
		 cout<<t1;
		 cout<<t2;
		 cout<<"\nСделаем вычетание t3=t1-t2";
		 t3=t1-t2;
		 cout<<t3;
getch();
getch();
}